# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dwayne/share/shared/test6_network_audio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dwayne/share/shared/test6_network_audio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dwayne/share/shared/test6_network_audio/CMakeFiles /home/dwayne/share/shared/test6_network_audio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dwayne/share/shared/test6_network_audio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client_main

# Build rule for target.
client_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_main
.PHONY : client_main

# fast build rule for target.
client_main/fast:
	$(MAKE) -f CMakeFiles/client_main.dir/build.make CMakeFiles/client_main.dir/build
.PHONY : client_main/fast

#=============================================================================
# Target rules for targets named server_main

# Build rule for target.
server_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server_main
.PHONY : server_main

# fast build rule for target.
server_main/fast:
	$(MAKE) -f CMakeFiles/server_main.dir/build.make CMakeFiles/server_main.dir/build
.PHONY : server_main/fast

client.o: client.cpp.o

.PHONY : client.o

# target to build an object file
client.cpp.o:
	$(MAKE) -f CMakeFiles/client_main.dir/build.make CMakeFiles/client_main.dir/client.cpp.o
.PHONY : client.cpp.o

client.i: client.cpp.i

.PHONY : client.i

# target to preprocess a source file
client.cpp.i:
	$(MAKE) -f CMakeFiles/client_main.dir/build.make CMakeFiles/client_main.dir/client.cpp.i
.PHONY : client.cpp.i

client.s: client.cpp.s

.PHONY : client.s

# target to generate assembly for a file
client.cpp.s:
	$(MAKE) -f CMakeFiles/client_main.dir/build.make CMakeFiles/client_main.dir/client.cpp.s
.PHONY : client.cpp.s

client_main.o: client_main.cpp.o

.PHONY : client_main.o

# target to build an object file
client_main.cpp.o:
	$(MAKE) -f CMakeFiles/client_main.dir/build.make CMakeFiles/client_main.dir/client_main.cpp.o
.PHONY : client_main.cpp.o

client_main.i: client_main.cpp.i

.PHONY : client_main.i

# target to preprocess a source file
client_main.cpp.i:
	$(MAKE) -f CMakeFiles/client_main.dir/build.make CMakeFiles/client_main.dir/client_main.cpp.i
.PHONY : client_main.cpp.i

client_main.s: client_main.cpp.s

.PHONY : client_main.s

# target to generate assembly for a file
client_main.cpp.s:
	$(MAKE) -f CMakeFiles/client_main.dir/build.make CMakeFiles/client_main.dir/client_main.cpp.s
.PHONY : client_main.cpp.s

server.o: server.cpp.o

.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/server_main.dir/build.make CMakeFiles/server_main.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i

.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/server_main.dir/build.make CMakeFiles/server_main.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s

.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/server_main.dir/build.make CMakeFiles/server_main.dir/server.cpp.s
.PHONY : server.cpp.s

server_main.o: server_main.cpp.o

.PHONY : server_main.o

# target to build an object file
server_main.cpp.o:
	$(MAKE) -f CMakeFiles/server_main.dir/build.make CMakeFiles/server_main.dir/server_main.cpp.o
.PHONY : server_main.cpp.o

server_main.i: server_main.cpp.i

.PHONY : server_main.i

# target to preprocess a source file
server_main.cpp.i:
	$(MAKE) -f CMakeFiles/server_main.dir/build.make CMakeFiles/server_main.dir/server_main.cpp.i
.PHONY : server_main.cpp.i

server_main.s: server_main.cpp.s

.PHONY : server_main.s

# target to generate assembly for a file
server_main.cpp.s:
	$(MAKE) -f CMakeFiles/server_main.dir/build.make CMakeFiles/server_main.dir/server_main.cpp.s
.PHONY : server_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... client_main"
	@echo "... server_main"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... client_main.o"
	@echo "... client_main.i"
	@echo "... client_main.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... server_main.o"
	@echo "... server_main.i"
	@echo "... server_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

